CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
TOOL_ROOTS := champsim_tracer

PIN_ROOT=pin-3.22-98547-g7a303a835-gcc-linux
include $(CONFIG_ROOT)/makefile.config
include $(TOOLS_ROOT)/Config/makefile.default.rules

